apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r16a-cloud-uploads-nfs
  namespace: r16a-cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 500Gi
