apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r16a-cloud-uploads
  namespace: r16a-cloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
